---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalpa/cf-cli-resource
    tag: latest

inputs:
- name: Workshops-2.0

params:
  TERM: dumb

run:
  path: Workshops-2.0/pipelines/tasks/destroy-workshop-env/task.sh
