---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalpa/workshop2.0
    tag: latest

inputs:
- name: Workshops-2.0

params:
  TERM: dumb

run:
  path: Workshops-2.0/pipelines/tasks/destroy-student-pipelines/task.sh
